# Generated by Django 5.2.12 on 2026-03-22 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercoinwallet',
            name='iscoin2',
        ),
        migrations.CreateModel(
            name='userCoinwallet2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.CharField(blank=True, default='0.00000', null=True)),
                ('walletaddress', models.CharField(blank=True, null=True)),
                ('iscoin2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.coin2')),
            ],
        ),
        migrations.AddField(
            model_name='usercoin',
            name='iscoin2',
            field=models.ManyToManyField(to='app.usercoinwallet2'),
        ),
    ]
