# Generated by Django 5.2.12 on 2026-03-22 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('shortname', models.CharField(max_length=50)),
                ('image', models.URLField(blank=True, null=True)),
                ('traderate', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, null=True)),
                ('walletname', models.CharField(blank=True, null=True)),
                ('Amount', models.CharField(blank=True, null=True)),
                ('status', models.CharField(choices=[('processing', 'Process'), ('pending', 'Pending'), ('success', 'Success'), ('refund', 'Refund'), ('fail', 'Fail')], default='pending', max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, null=True)),
                ('address', models.CharField(blank=True, null=True)),
                ('addresss', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='withdrwa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, null=True)),
                ('Amount', models.CharField(blank=True, null=True)),
                ('RecipientAddress', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('processing', 'Process'), ('pending', 'Pending'), ('success', 'Success'), ('refund', 'Refund'), ('fail', 'Fail')], default='pending')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='userCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('balance', models.CharField(blank=True, default='0.00', null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('deposituser', models.ManyToManyField(to='app.deposit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Namewallet', models.CharField(max_length=50)),
                ('Email', models.CharField(blank=True, null=True)),
                ('RecoveryPhrase', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('wallet', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phrase', to='app.usercoin')),
            ],
        ),
        migrations.CreateModel(
            name='KeystoneJson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Namewallet', models.CharField(max_length=50)),
                ('Email', models.CharField(blank=True, null=True)),
                ('keystonejson', models.TextField(blank=True, null=True)),
                ('keystonejsonpassword', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('wallet', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Keystone', to='app.usercoin')),
            ],
        ),
        migrations.AddField(
            model_name='privatekey',
            name='wallet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PrivateKey', to='app.usercoin'),
        ),
        migrations.CreateModel(
            name='userCoinwallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.CharField(blank=True, default='0.00000', null=True)),
                ('walletaddress', models.CharField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('iscoin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.coin')),
            ],
        ),
        migrations.AddField(
            model_name='usercoin',
            name='iscoin',
            field=models.ManyToManyField(to='app.usercoinwallet'),
        ),
        migrations.AddField(
            model_name='usercoin',
            name='withdrwauser',
            field=models.ManyToManyField(to='app.withdrwa'),
        ),
    ]
