# Generated by Django 5.2.12 on 2026-03-22 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_coin_deposit_wallet_withdrwa_usercoin_phrase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('shortname', models.CharField(max_length=50)),
                ('image', models.URLField(blank=True, null=True)),
                ('traderate', models.CharField(blank=True, null=True)),
                ('traderates', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='usercoinwallet',
            name='iscoin2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.coin2'),
        ),
    ]
