# Generated by Django 5.2.12 on 2026-03-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_usercoinwallet_iscoin2_usercoinwallet2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoin',
            name='session_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
