# Generated by Django 5.2.12 on 2026-03-22 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_coin2_usercoinwallet_iscoin2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoin',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usercoinwallet',
            name='iscoin2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.coin2'),
        ),
    ]
