# Generated by Django 5.2.12 on 2026-04-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_usercoin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoin',
            name='deposituser',
            field=models.ManyToManyField(blank=True, to='app.deposit'),
        ),
        migrations.AlterField(
            model_name='usercoin',
            name='iscoin',
            field=models.ManyToManyField(blank=True, to='app.usercoinwallet'),
        ),
        migrations.AlterField(
            model_name='usercoin',
            name='iscoin2',
            field=models.ManyToManyField(blank=True, to='app.usercoinwallet2'),
        ),
        migrations.AlterField(
            model_name='usercoin',
            name='withdrwauser',
            field=models.ManyToManyField(blank=True, to='app.withdrwa'),
        ),
    ]
