# Generated by Django 5.2.12 on 2026-04-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_usercoin_deposituser_alter_usercoin_iscoin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoinwallet2',
            name='username',
            field=models.CharField(blank=True, default='0.00000', null=True),
        ),
    ]
